const methodConfig = {
    "频数":{
        name:'频数',
        analysisParameter:{
        },
        columns:{
            dateType:['string', 'enum', 'number'],
            columnsContent:[
                {
                    id:'x',
                    label:'x定量',
                    datatype:['string','number'],
                    tooltip:'x的分析哦',
                    minrowCount:1,
                    maxrowCount:2,
                },
                {
                    id:'y',
                    label:'Y定量',
                    datatype:['enum'],
                    tooltip:'玉面小飞龙',
                    minrowCount:1,
                    maxrowCount:1
                },
                {
                    id:'options',
                    label:'可选项',
                    datatype:['string'],
                    tooltip:'可选的项啊',
                    minrowCount:0,
                    maxrowCount:10
                }
            ]
        }
    },
    "分类汇总":{
        name:'频数',
        analysisParameter:{
            type:'option',
            options:[
                '汇总类型',
                '平均值',
                '百分数',
            ]
        },
        columns:{
            dateType:['string', 'enum', 'number'],
            columnsContent:[
                {
                    id:'x',
                    label:'x定量',
                    datatype:['string','number'],
                    tooltip:'x的分析哦',
                    minrowCount:1,
                    maxrowCount:2,
                },
                {
                    id:'y',
                    label:'Y定量',
                    datatype:['enum'],
                    tooltip:'玉面小飞龙',
                    minrowCount:1,
                    maxrowCount:1
                },
                {
                    id:'options',
                    label:'可选项',
                    datatype:['string'],
                    tooltip:'可选的项啊',
                    minrowCount:0,
                    maxrowCount:10
                }
            ]
        }
    },
    "相关":{
        name:'相关',
        analysisParameter:{
            type:'option',
            options:[
                'Person相关系数',
                'Spearman相关系数',
                'KendaII相关系数',
            ]
        },
        columns:{
            dateType:['string', 'enum', 'number'],
            columnsContent:[
                {
                    id:'x',
                    label:'x定量',
                    datatype:['string','number'],
                    tooltip:'x的分析哦',
                    minrowCount:1,
                    maxrowCount:2,
                },
                {
                    id:'y',
                    label:'Y定量',
                    datatype:['enum'],
                    tooltip:'玉面小飞龙',
                    minrowCount:1,
                    maxrowCount:1
                },
                {
                    id:'options',
                    label:'可选项',
                    datatype:['string'],
                    tooltip:'可选的项啊',
                    minrowCount:0,
                    maxrowCount:10
                }
            ]
        }
    },
    "线性回归":{
        name:'线性回归',
        analysisParameter:{
            type:'check',
            label:'保存残差和预测值'
        },
        columns:{
            dateType:['string', 'enum', 'number'],
            columnsContent:[
                {
                    id:'x',
                    label:'x定量',
                    datatype:['string','number'],
                    tooltip:'x的分析哦',
                    minrowCount:1,
                    maxrowCount:2,
                },
                {
                    id:'y',
                    label:'Y定量',
                    datatype:['enum'],
                    tooltip:'玉面小飞龙',
                    minrowCount:1,
                    maxrowCount:1
                },
                {
                    id:'options',
                    label:'可选项',
                    datatype:['string'],
                    tooltip:'可选的项啊',
                    minrowCount:0,
                    maxrowCount:10
                }
            ]
        }
    },
    "单样本T检验":{
        name:'单样本T检验',
        analysisParameter:{
            type:'number',
            placeholder:'输入对比数字,默认为0'
        },
        columns:{
            dateType:['string', 'enum', 'number'],
            columnsContent:[
                {
                    id:'x',
                    label:'x定量',
                    datatype:['string','number'],
                    tooltip:'x的分析哦',
                    minrowCount:1,
                    maxrowCount:2,
                },
                {
                    id:'y',
                    label:'Y定量',
                    datatype:['enum'],
                    tooltip:'玉面小飞龙',
                    minrowCount:1,
                    maxrowCount:1
                },
                {
                    id:'options',
                    label:'可选项',
                    datatype:['string'],
                    tooltip:'可选的项啊',
                    minrowCount:0,
                    maxrowCount:10
                }
            ]
        }
    },
};

const columns ={
    string:[ {
        id:'1',
        name:'患者主索引',
        type:'string'
    },
        {
            id:'2',
            name:'姓名',
            type:'string'
        },

        {
            id:'4',
            name:'生日',
            type:'string'
        },
        {
            id:'7',
            name:'测试7',
            type:'string'
        },
        {
            id:'8',
            name:'测试8',
            type:'string'
        },
        {
            id:'9',
            name:'测试9',
            type:'string'
        },
        {
            id:'10',
            name:'测试10',
            type:'string'
        },
        {
            id:'11',
            name:'测试11',
            type:'string'
        }
    ],
    enum:[ {
        id:'3',
        name:'性别',
        type:'enum2'
    },{
        id:'5',
        name:'检验类型',
        type:'enumN'
    },],
    number:[
        {
            id:'6',
            name:'检验结果',
            type:'number'
        },
        {
            id:'14',
            name:'血压',
            type:'number'
        }
    ]
};
let Config = {
    methodConfig:methodConfig,
    columns:columns
};
export default Config;